name = "miguel-ai-worker"
main = "src/index.ts"
compatibility_date = "2025-12-18"
compatibility_flags = ["nodejs_compat"]

[vars]
GEMINI_API_KEY = "AIzaSyBdQkdJykr3VLdUw_QmK_B5MstIYOjXtWo"
MISTRAL_API_KEY = "RlLdYVXJncGE7GyZ4c0NAZ8aRYP36Snv"

